apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: olvty96f9-python 
  janus-idp.io/tekton: olvty96f9-python
  backstage.io/kubernetes-id: olvty96f9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: olvty96f9-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml